global:
  scrape_interval: 30s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: lambdadb
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'lambdadb:8000'

