model:
  adres: u
  buurtcode: b
  buurtnaam: r
  gebruiksdoelen: r
  gemeentecode: b
  gemeentenaam: r
  group_id_2020: u
  index: '0'
  labelscore_definitief: b
  labelscore_voorlopig: b
  numid: u
  oppervlakte: u
  p6_gas_aansluitingen_2020: u
  p6_gasm3_2020: u
  p6_kwh_2020: u
  p6_totaal_pandoppervlak_m2: u
  pand_bouwjaar: u
  pand_gas_aansluitingen: u
  pand_gas_ean_aansluitingen: u
  pid: u
  point: g
  postcode: u
  provinciecode: b
  provincienaam: r
  vid: u
  wijkcode: b
  wijknaam: r
  woning_type: b
  woningequivalent: u
