model:
  adres: u
  buurtcode: b
  buurtnaam: r
  energieklasse: b
  gebruiksdoelen: r
  gemeentecode: b
  gemeentenaam: r
  group_id_2020: u
  huisletter: r
  huisnummer: r
  huisnummertoevoeging: r
  index: '0'
  labelscore_definitief: b
  labelscore_voorlopig: b
  numid: u
  oppervlakte: r
  p6_gas_aansluitingen_2020: r
  p6_gasm3_2020: r
  p6_kwh_2020: r
  p6_totaal_pandoppervlak_m2: r
  pand_bouwjaar: r
  pand_gas_aansluitingen: r
  pand_gas_ean_aansluitingen: r
  pid: b
  point: g
  postcode: b
  provinciecode: b
  provincienaam: r
  straat: r
  vid: r
  wijkcode: b
  wijknaam: r
  woning_type: b
  woningequivalent: r
